name: Build Android GKI Kernel

on:
  workflow_dispatch:
    inputs:
      GKI_DEV:
        description: 'GKI 内核分支，例如 android14-6.1-2024-10'
        required: true
        default: 'android14-6.1-2024-10'
      KSU_BRANCH:
        description: '选择 KernelSU 分支'
        required: true
        default: 'y'
        type: choice
        options:
          - y
          - n
      APPLY_SUSFS:
        description: '是否启用 SUSFS'
        required: true
        default: 'y'
        type: choice
        options:
          - y
          - n
      APPLY_LZ4KD:
        description: '是否启用 LZ4KD'
        required: true
        default: 'y'
        type: choice
        options:
          - y
          - n
      APPLY_KPROBES:
        description: '是否启用 KPROBES'
        required: true
        default: 'y'
        type: choice
        options:
          - y
          - n
      USE_PATCH_LINUX:
        description: '是否启用 KPM Patch'
        required: true
        default: 'n'
        type: choice
        options:
          - y
          - n
      APPLY_BBR:
        description: '是否启用 BBR 拥塞控制'
        required: true
        default: 'n'
        type: choice
        options:
          - y
          - n
          - d
      APPLY_SSG:
        description: '是否启用 SSG IO 调度器'
        required: true
        default: 'n'
        type: choice
        options:
          - y
          - n

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GKI_DEV: ${{ github.event.inputs.GKI_DEV }}
      KSU_BRANCH: ${{ github.event.inputs.KSU_BRANCH }}
      APPLY_SUSFS: ${{ github.event.inputs.APPLY_SUSFS }}
      APPLY_LZ4KD: ${{ github.event.inputs.APPLY_LZ4KD }}
      APPLY_KPROBES: ${{ github.event.inputs.APPLY_KPROBES }}
      USE_PATCH_LINUX: ${{ github.event.inputs.USE_PATCH_LINUX }}
      APPLY_BBR: ${{ github.event.inputs.APPLY_BBR }}
      APPLY_SSG: ${{ github.event.inputs.APPLY_SSG }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install curl bison flex make binutils dwarves git lld pahole zip perl make gcc python3 python-is-python3 bc libssl-dev libelf-dev -y
          
      - name: Make output directory
        run: mkdir -p out

      - name: Run build script
        run: |
          chmod +x ./locals/build.sh
          ./locals/build.sh
