name: SukiSU Ultra，KernelSU Next构建

on:
  workflow_dispatch:
    inputs:
      GKI_DEV:
        description: 'GKI 内核分支'
        required: true
        default: 'android14-6.1-2024-10'
      SUKUSU:
        description: '是否使用 SukiSU'
        required: false
        default: 'y'
      APPLY_SUSFS:
        description: '是否启用 SUSFS'
        required: false
        default: 'y'
      APPLY_SSG:
        description: '是否启用 SSG IO'
        required: false
        default: 'n'
      APPLY_BBR:
        description: '是否启用 BBR 拥塞控制'
        required: false
        default: 'd'
      APPLY_BETTERNET:
        description: '是否启用网络增强'
        required: false
        default: 'y'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GKI_DEV: ${{ github.event.inputs.GKI_DEV }}
      SUKUSU: ${{ github.event.inputs.SUKUSU }}
      APPLY_SUSFS: ${{ github.event.inputs.APPLY_SUSFS }}
      APPLY_SSG: ${{ github.event.inputs.APPLY_SSG }}
      APPLY_BBR: ${{ github.event.inputs.APPLY_BBR }}
      APPLY_BETTERNET: ${{ github.event.inputs.APPLY_BETTERNET }}

    steps:
      - name: 检查储存库
        uses: actions/checkout@v4

      - name: 执行开始构建脚本
        run: 
          chmod +x local/build.sh
          ./local/build.sh

      - name: 上传内核
        uses: actions/upload-artifact@v4
        with:
          name: kernel
          path: common/out/kernel.zip
