name: GKI内核构建

on:
  workflow_dispatch:
    inputs:
      GKI_DEV:
        description: '请输入gki内核分支(e.g., android14-6.1-2024-10)'
        required: true
        default: 'android14-6.1-2024-10'
      SUKISU:
        description: 'KernelSU分支'
        required: true
        default: 'SukiSU Ultra'
        type: choice
        options: [SukiSU Ultra, Kernel Next]
      APPLY_SSG:
        description: '是否启用 SSG IO 调度'
        required: true
        default: 'n'
        type: choice
        options: [y, n]
      APPLY_SUSFS:
        description: '是否启用 SUSFS'
        required: true
        default: 'y'
        type: choice
        options: [y, n]
      APPLY_KPM:
        description: '是否启用 KPM'
        required: true
        default: 'y'
        type: choice
        options: [y, n]
      APPLY_BETTERNET:
        description: '是否启用网络优化'
        required: true
        default: 'y'
        type: choice
        options: [y, n]
      APPLY_BBR:
        description: '是否引入BBR网络阻塞算法'
        required: true
        default: 'd'
        type: choice
        options: [y, n, d]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 环境变量值
        run: |
          echo "GKI_DEV=${{ github.event.inputs.GKI_DEV }}" >> $GITHUB_ENV
          echo "SUKISU=${{ github.event.inputs.SUKISU }}" >> $GITHUB_ENV
          echo "APPLY_SSG=${{ github.event.inputs.APPLY_SSG }}" >> $GITHUB_ENV
          echo "APPLY_SUSFS=${{ github.event.inputs.APPLY_SUSFS }}" >> $GITHUB_ENV
          echo "APPLY_KPM=${{ github.event.inputs.APPLY_KPM }}" >> $GITHUB_ENV
          echo "APPLY_BETTERNET=${{ github.event.inputs.APPLY_BETTERNET }}" >> $GITHUB_ENV
          echo "APPLY_BBR=${{ github.event.inputs.APPLY_BBR }}" >> $GITHUB_ENV

      - name: 安装编译环境
        run: sudo apt-get update && sudo apt-get install -y curl bison flex make binutils dwarves git lld pahole zip perl gcc python3 python-is-python3 bc libssl-dev libelf-dev

      - name: 执行编译脚本
        run: |
          chmod +x local/build.sh
          bash -x local/build.sh

      - name: 上传内核
        uses: actions/upload-artifact@v4
        with:
          name: kernel
          path: common/out/kernel.zip
