name: Android Kernel Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Kernel with SukiSU/SUSFS/SSG/LZ4KD/842
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y bc bison flex git make libssl-dev \
          python3 python3-pip rsync unzip wget cpio gcc \
          libncurses-dev libelf-dev curl device-tree-compiler zip

    - name: Clone Kernel & Toolchains
      run: |
        git clone https://android.googlesource.com/kernel/common -b android14-6.1-2024-10 --depth=1 common
        cd common
        git clone https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 -b android14-release --depth=1 llvm
        git clone https://github.com/xiaoxian8/AnyKernel3.git --depth=1
        echo "PATH=$PWD/llvm/clang-r487747c/bin:$PATH" >> $GITHUB_ENV
        echo "DEFCONFIG_FILE=$PWD/arch/arm64/configs/gki_defconfig" >> $GITHUB_ENV

    - name: Apply Patches and Configure
      working-directory: common
      run: |
        rm android/abi_gki_protected_exports_* || true
        sed -i 's/ -dirty//g' scripts/setlocalversion
        echo ">>> 添加SukiSU 和 SUSFS"
        curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-main
        git clone https://github.com/SukiSU-Ultra/SukiSU_patch.git --depth=1
        git clone https://github.com/xiaoxian8/ssg_patch.git --depth=1
        git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android14-6.1 --depth=1
        cp -r ssg_patch/* ./
        patch -p1 < ssg.patch
        patch -p1 < SukiSU_patch/hooks/syscall_hooks.patch
        patch -p1 < SukiSU_patch/69_hide_stuff.patch
        patch -p1 -F3 < SukiSU_patch/other/zram/zram_patch/6.1/lz4kd.patch
        patch -p1 -F3 < SukiSU_patch/other/zram/zram_patch/6.1/lz4k_oplus.patch
        cp -r SukiSU_patch/other/zram/lz4k/* ./
        cp -r SukiSU_patch/other/zram/lz4k_oplus ./lib
        cp -r susfs4ksu/kernel_patches/* ./
        patch -p1 < susfs4ksu/kernel_patches/50_add_susfs_in_gki-android14-6.1.patch

    - name: Append Kernel Config
      working-directory: common
      run: |
        CONFIG=$DEFCONFIG_FILE
        cat >> "$CONFIG" <<EOF
CONFIG_LTO_CLANG=y
CONFIG_ARCH_SUPPORTS_LTO_CLANG=y
CONFIG_ARCH_SUPPORTS_LTO_CLANG_THIN=y
CONFIG_HAS_LTO_CLANG=y
CONFIG_LTO_CLANG_THIN=y
CONFIG_LTO=y
CONFIG_LOCALVERSION="-xiaoxian"
CONFIG_KSU=y
CONFIG_KSU_SUSFS=y
CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y
CONFIG_KSU_SUSFS_SUS_PATH=y
CONFIG_KSU_SUSFS_SUS_MOUNT=y
CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y
CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y
CONFIG_KSU_SUSFS_SUS_KSTAT=y
CONFIG_KSU_SUSFS_TRY_UMOUNT=y
CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y
CONFIG_KSU_SUSFS_SPOOF_UNAME=y
CONFIG_KSU_SUSFS_ENABLE_LOG=y
CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y
CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y
CONFIG_KSU_SUSFS_OPEN_REDIRECT=y
CONFIG_KSU_KPROBES_HOOK=y
CONFIG_KSU_MANUAL_HOOK=y
CONFIG_KSU_SUSFS_SUS_SU=n
CONFIG_KPM=y
CONFIG_CRYPTO_LZ4K_OPLUS=y
CONFIG_ZSMALLOC=y
CONFIG_CRYPTO_LZ4HC=y
CONFIG_CRYPTO_LZ4K=y
CONFIG_CRYPTO_LZ4KD=y
CONFIG_CRYPTO_842=y
CONFIG_ZRAM_DEF_COMP="lz4"
CONFIG_TCP_CONG_ADVANCED=y
CONFIG_TCP_CONG_BBR=y
CONFIG_TCP_CONG_CUBIC=y
CONFIG_TCP_CONG_VEGAS=y
CONFIG_TCP_CONG_NV=y
CONFIG_TCP_CONG_WESTWOOD=y
CONFIG_TCP_CONG_HTCP=y
CONFIG_TCP_CONG_BRUTAL=y
CONFIG_DEFAULT_TCP_CONG=bbr
CONFIG_MQ_IOSCHED_SSG=y
CONFIG_MQ_IOSCHED_SSG_CGROUP=y
CONFIG_BPF_STREAM_PARSER=y
CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=y
CONFIG_NETFILTER_XT_SET=y
CONFIG_IP_SET=y
CONFIG_IP_SET_MAX=65534
CONFIG_IP_SET_BITMAP_IP=y
CONFIG_IP_SET_BITMAP_IPMAC=y
CONFIG_IP_SET_BITMAP_PORT=y
CONFIG_IP_SET_HASH_IP=y
CONFIG_IP_SET_HASH_IPMARK=y
CONFIG_IP_SET_HASH_IPPORT=y
CONFIG_IP_SET_HASH_IPPORTIP=y
CONFIG_IP_SET_HASH_IPPORTNET=y
CONFIG_IP_SET_HASH_IPMAC=y
CONFIG_IP_SET_HASH_MAC=y
CONFIG_IP_SET_HASH_NETPORTNET=y
CONFIG_IP_SET_HASH_NET=y
CONFIG_IP_SET_HASH_NETNET=y
CONFIG_IP_SET_HASH_NETPORT=y
CONFIG_IP_SET_HASH_NETIFACE=y
CONFIG_IP_SET_LIST_SET=y
CONFIG_IP6_NF_NAT=y
CONFIG_IP6_NF_TARGET_MASQUERADE=y
EOF

    - name: Build Kernel & Modules
      working-directory: common
      run: |
        args=(-j$(nproc) O=out ARCH=arm64 LLVM=1 DEPMOD=depmod DTC=dtc)
        make "${args[@]}" mrproper
        make "${args[@]}" gki_defconfig
        make "${args[@]}" Image.lz4 modules
        make "${args[@]}" INSTALL_MOD_PATH=modules modules_install

    - name: Pack Flashable Kernel ZIP
      working-directory: common
      run: |
        chmod +x SukiSU_patch/kpm/patch_linux
        cp $(find out -type f -name "Image") ./
        ./SukiSU_patch/kpm/patch_linux
        mv -v oImage AnyKernel3/Image
        cd AnyKernel3
        zip -r9v ../out/kernel.zip *
        rm Image ../Image

    - name: Upload Kernel.zip
      uses: actions/upload-artifact@v3
      with:
        name: GKI-Kernel-ZIP
        path: common/